import { readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import YAML from "yaml";
import { SowConfigSchema, type SowConfigParsed } from "./schema.js";
import type {
  SamplingConfig,
  SanitizationConfig,
  ExportFormat,
} from "../types.js";
import { getSowDir, readConnectorMetadata } from "../branching/storage.js";

const CONFIG_FILE_NAMES = [".sow.yml", ".sow.yaml"];
const GLOBAL_CONFIG_DIR = join(
  process.env.HOME || process.env.USERPROFILE || "~",
  ".sow",
);
const GLOBAL_CONFIG_PATH = join(GLOBAL_CONFIG_DIR, "config.json");

interface GlobalConfig {
  token?: string;
}

export interface ProjectState {
  defaultConnector?: string;
}

/**
 * Resolve ${ENV_VAR} references in a string.
 */
function resolveEnvVars(value: string): string {
  return value.replace(/\$\{(\w+)\}/g, (_, name) => {
    return process.env[name] || "";
  });
}

/**
 * Load .sow.yml from the given directory (or cwd).
 */
export function loadProjectConfig(
  dir = process.cwd(),
  explicitPath?: string,
): SowConfigParsed | null {
  const paths = explicitPath ? [explicitPath] : CONFIG_FILE_NAMES.map((f) => join(dir, f));

  for (const path of paths) {
    if (existsSync(path)) {
      const raw = readFileSync(path, "utf-8");
      const parsed = YAML.parse(raw);

      // Resolve env vars in connection string
      if (parsed?.source?.connection) {
        parsed.source.connection = resolveEnvVars(parsed.source.connection);
      }

      const result = SowConfigSchema.safeParse(parsed);
      if (result.success) return result.data;

      throw new Error(
        `Invalid .sow.yml: ${result.error.issues.map((i) => i.message).join(", ")}`,
      );
    }
  }

  return null;
}

/**
 * Load global config from ~/.sow/config.json
 */
export function loadGlobalConfig(): GlobalConfig {
  if (!existsSync(GLOBAL_CONFIG_PATH)) return {};

  try {
    const raw = readFileSync(GLOBAL_CONFIG_PATH, "utf-8");
    return JSON.parse(raw) as GlobalConfig;
  } catch {
    return {};
  }
}

/**
 * Save global config to ~/.sow/config.json
 */
export function saveGlobalConfig(config: GlobalConfig): void {
  mkdirSync(GLOBAL_CONFIG_DIR, { recursive: true });
  writeFileSync(GLOBAL_CONFIG_PATH, JSON.stringify(config, null, 2), "utf-8");
}

/**
 * Read the destructive-Supabase opt-in from `.sow.yml` for the given
 * project directory. Returns true only if the project explicitly set
 * `providers.supabase.destructive_consent: true`. Any other state —
 * no config file, no providers section, field absent, field false,
 * malformed YAML — returns false.
 *
 * This is one of three gates on the Supabase branch provider. See
 * `packages/core/src/branching/providers/supabase.ts` for the full
 * gating logic.
 */
export function loadSupabaseDestructiveConsent(dir = process.cwd()): boolean {
  try {
    const cfg = loadProjectConfig(dir);
    return cfg?.providers?.supabase?.destructive_consent === true;
  } catch {
    // Malformed config → treat as no consent. Fail-safe.
    return false;
  }
}

/**
 * Load project state from .sow/config.json (auto-managed, not user-edited).
 */
export function loadProjectState(): ProjectState {
  const statePath = join(getSowDir(), "config.json");
  if (!existsSync(statePath)) return {};
  try {
    const raw = readFileSync(statePath, "utf-8");
    return JSON.parse(raw) as ProjectState;
  } catch {
    return {};
  }
}

/**
 * Save project state to .sow/config.json.
 */
export function saveProjectState(state: ProjectState): void {
  const dir = getSowDir();
  mkdirSync(dir, { recursive: true });
  const existing = loadProjectState();
  const merged = { ...existing, ...state };
  writeFileSync(join(dir, "config.json"), JSON.stringify(merged, null, 2), "utf-8");
}

/**
 * Generate a default .sow.yml content string.
 */
export function generateDefaultConfig(opts?: {
  maxRowsPerTable?: number;
  seed?: number;
  excludeTables?: string[];
  sanitize?: boolean;
}): string {
  const maxRows = opts?.maxRowsPerTable ?? 50;
  const seed = opts?.seed ?? 42;
  const excludes = opts?.excludeTables?.length
    ? opts.excludeTables
    : ["_migrations", "_prisma_migrations", "spatial_ref_sys"];
  const sanitize = opts?.sanitize ?? true;

  const excludeLines = excludes.map((t) => `    - ${t}`).join("\n");

  return `# .sow.yml — project-level configuration
# Generated by sow connect. Edit as needed.
version: 1

source:
  connection: \${DATABASE_URL}

sampling:
  maxRowsPerTable: ${maxRows}
  seed: ${seed}
  excludeTables:
${excludeLines}

sanitization:
  enabled: ${sanitize}
`;
}

/**
 * Merge CLI flags with project config, global config, and project state.
 * Priority: CLI flags > .sow.yml > DATABASE_URL > .sow/config.json > defaults
 */
export function mergeConfig(
  cliFlags: Record<string, unknown>,
  projectConfig: SowConfigParsed | null,
  _globalConfig: GlobalConfig,
): {
  connectionString: string;
  samplingConfig: SamplingConfig;
  sanitizationConfig: SanitizationConfig;
  exportFormat: ExportFormat;
  outputPath: string;
} {
  const projectState = loadProjectState();
  let defaultConnectorConn = "";
  if (projectState.defaultConnector) {
    const meta = readConnectorMetadata(projectState.defaultConnector);
    if (meta) defaultConnectorConn = meta.connectionString;
  }

  const connectionString =
    (cliFlags.connectionString as string) ||
    projectConfig?.source?.connection ||
    process.env.DATABASE_URL ||
    defaultConnectorConn ||
    "";

  const samplingConfig: SamplingConfig = {
    maxRowsPerTable:
      (cliFlags.maxRows as number) ||
      projectConfig?.sampling?.maxRowsPerTable ||
      200,
    seed: (cliFlags.seed as number) || projectConfig?.sampling?.seed || 42,
    includeEdgeCases:
      projectConfig?.sampling?.includeEdgeCases ?? true,
    excludeTables:
      (cliFlags.exclude as string)?.split(",").map((s) => s.trim()) ||
      projectConfig?.sampling?.excludeTables ||
      [],
    includeTables:
      (cliFlags.include as string)?.split(",").map((s) => s.trim()) ||
      projectConfig?.sampling?.includeTables ||
      [],
  };

  const sanitizationConfig: SanitizationConfig = {
    enabled: !cliFlags.noSanitize && (projectConfig?.sanitization?.enabled ?? true),
    rules: (projectConfig?.sanitization?.rules ?? []).map((r) => ({
      table: r.table,
      column: r.column,
      type: r.type as any,
    })),
    skipColumns: projectConfig?.sanitization?.skipColumns ?? [],
  };

  const exportFormat =
    (cliFlags.format as ExportFormat) ||
    projectConfig?.export?.format ||
    "sql";

  const outputPath =
    (cliFlags.output as string) ||
    projectConfig?.export?.outputPath ||
    "./sow-output";

  return {
    connectionString,
    samplingConfig,
    sanitizationConfig,
    exportFormat,
    outputPath,
  };
}
