import { mkdirSync, writeFileSync, readFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import type { SchemaInfo, SanitizedTable, ExportResult } from "../types.js";
import { exportSQL } from "./sql.js";

const DOCKER_COMPOSE_TEMPLATE = `# Generated by sow
services:
  sow-test-db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
`;

export function exportDocker(
  schema: SchemaInfo,
  tables: SanitizedTable[],
  dependencyOrder: string[],
  outputPath: string,
): ExportResult {
  mkdirSync(outputPath, { recursive: true });

  // Generate init.sql (reuse SQL exporter, but to a temp name)
  const sqlResult = exportSQL(schema, tables, dependencyOrder, outputPath);

  const sqlPath = join(outputPath, "sow.sql");
  const initPath = join(outputPath, "init.sql");

  if (sqlPath !== initPath) {
    const content = readFileSync(sqlPath, "utf-8");
    writeFileSync(initPath, content, "utf-8");
    unlinkSync(sqlPath);
  }

  // Write docker-compose.yml
  const composePath = join(outputPath, "docker-compose.yml");
  writeFileSync(composePath, DOCKER_COMPOSE_TEMPLATE, "utf-8");

  return {
    format: "docker",
    outputPath,
    files: [composePath, initPath],
    totalSize: sqlResult.totalSize + Buffer.byteLength(DOCKER_COMPOSE_TEMPLATE, "utf-8"),
    tableCount: sqlResult.tableCount,
    rowCount: sqlResult.rowCount,
  };
}
