import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type {
  SchemaInfo,
  SanitizedTable,
  ExportResult,
  TableInfo,
  ColumnInfo,
} from "../types.js";
import { PostgresTypeMapper } from "../adapters/type-mapper.js";
import { quoteIdent } from "../sql/identifiers.js";

/**
 * Render a column's Postgres type. User-defined types like enums are
 * case-sensitive in Postgres and must be double-quoted when referenced,
 * otherwise the parser folds them to lowercase and errors with
 * `type "leadsource" does not exist`. Built-in types (int4, text, ...)
 * are emitted as-is.
 */
function renderColumnType(rawType: string, enumNames: Set<string>): string {
  const isArray = rawType.endsWith("[]");
  const base = isArray ? rawType.slice(0, -2) : rawType;
  if (enumNames.has(base)) {
    return quoteIdent(base) + (isArray ? "[]" : "");
  }
  return rawType;
}

function columnDef(col: ColumnInfo, enumNames: Set<string>): string {
  let def = `  ${quoteIdent(col.name)} ${renderColumnType(col.type, enumNames)}`;
  if (!col.nullable) def += " NOT NULL";
  if (col.defaultValue && !col.isGenerated) def += ` DEFAULT ${col.defaultValue}`;
  return def;
}

function createTableSQL(table: TableInfo, enumNames: Set<string>): string {
  const cols = table.columns.map((c) => columnDef(c, enumNames)).join(",\n");
  let sql = `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n${cols}`;

  if (table.primaryKey.length > 0) {
    sql += `,\n  PRIMARY KEY (${table.primaryKey.map((k) => quoteIdent(k)).join(", ")})`;
  }

  sql += "\n);";
  return sql;
}

function insertSQL(
  table: TableInfo,
  rows: Record<string, unknown>[],
  typeMapper: PostgresTypeMapper,
): string {
  if (rows.length === 0) return "";

  const columns = table.columns.filter((c) => !c.isGenerated);
  const colNames = columns.map((c) => quoteIdent(c.name)).join(", ");

  const valueRows = rows.map((row) => {
    const vals = columns
      .map((col) => typeMapper.toInsertLiteral(row[col.name], col.type))
      .join(", ");
    return `(${vals})`;
  });

  return `INSERT INTO ${quoteIdent(table.name)} (${colNames}) VALUES\n${valueRows.join(",\n")};`;
}

export function exportSQL(
  schema: SchemaInfo,
  tables: SanitizedTable[],
  dependencyOrder: string[],
  outputPath: string,
): ExportResult {
  const enumNames = new Set(schema.enums.map((e) => e.name));
  const typeMapper = new PostgresTypeMapper(enumNames);
  const lines: string[] = [];

  lines.push("-- Generated by sow");
  lines.push(`-- ${new Date().toISOString()}`);
  lines.push("-- Using individual transactions so one bad row doesn't block the rest");
  lines.push("");

  // Extensions (skip provider-specific ones that don't exist in standard Postgres)
  const SKIP_EXTENSIONS = new Set([
    "supabase_vault", "pgsodium", "pg_graphql", "pgtle", "pg_stat_statements",
    "pg_stat_monitor", "pgaudit", "pgjwt", "pg_net", "plv8",
    "http", "pg_cron", "pg_hashids", "wrappers",
  ]);
  const filteredExtensions = schema.extensions.filter((ext) => !SKIP_EXTENSIONS.has(ext));
  for (const ext of filteredExtensions) {
    lines.push(`CREATE EXTENSION IF NOT EXISTS ${quoteIdent(ext)};`);
  }
  if (filteredExtensions.length > 0) lines.push("");

  // Enums
  for (const enumType of schema.enums) {
    const values = enumType.values
      .map((v) => `'${v.replace(/'/g, "''")}'`)
      .join(", ");
    lines.push(
      `DO $$ BEGIN CREATE TYPE ${quoteIdent(enumType.name)} AS ENUM (${values}); EXCEPTION WHEN duplicate_object THEN null; END $$;`,
    );
  }
  if (schema.enums.length > 0) lines.push("");

  // Sequences (must come before tables that reference them)
  const seqNames = new Set<string>();
  for (const table of schema.tables) {
    for (const col of table.columns) {
      if (col.defaultValue) {
        const match = col.defaultValue.match(/nextval\('([^']+)'::regclass\)/);
        if (match) seqNames.add(match[1]);
      }
    }
  }
  for (const seq of seqNames) {
    lines.push(`CREATE SEQUENCE IF NOT EXISTS ${quoteIdent(seq)};`);
  }
  if (seqNames.size > 0) lines.push("");

  // Tables in dependency order
  const tableInfoMap = new Map(schema.tables.map((t) => [t.name, t]));
  const dataMap = new Map(tables.map((t) => [t.table, t]));

  for (const tableName of dependencyOrder) {
    const tableInfo = tableInfoMap.get(tableName);
    if (!tableInfo) continue;

    lines.push(createTableSQL(tableInfo, enumNames));
    lines.push("");

    const data = dataMap.get(tableName);
    if (data && data.rows.length > 0) {
      const BATCH_SIZE = 100;
      for (let i = 0; i < data.rows.length; i += BATCH_SIZE) {
        lines.push(
          insertSQL(tableInfo, data.rows.slice(i, i + BATCH_SIZE), typeMapper),
        );
      }
      lines.push("");
    }
  }

  // Sync sequences to max ID values
  for (const tableName of dependencyOrder) {
    const tableInfo = tableInfoMap.get(tableName);
    if (!tableInfo) continue;
    for (const col of tableInfo.columns) {
      if (col.defaultValue) {
        const match = col.defaultValue.match(/nextval\('([^']+)'::regclass\)/);
        if (match) {
          lines.push(
            `SELECT setval('${match[1].replace(/'/g, "''")}', COALESCE((SELECT MAX(${quoteIdent(col.name)}) FROM ${quoteIdent(tableName)}), 1));`,
          );
        }
      }
    }
  }
  if (seqNames.size > 0) lines.push("");

  // Indexes (after data for performance)
  for (const index of schema.indexes) {
    const cols = index.columns.map((c) => quoteIdent(c)).join(", ");
    const unique = index.unique ? "UNIQUE " : "";
    lines.push(
      `CREATE ${unique}INDEX IF NOT EXISTS ${quoteIdent(index.name)} ON ${quoteIdent(index.table)} (${cols});`,
    );
  }
  if (schema.indexes.length > 0) lines.push("");

  lines.push("-- End of sow init");

  const content = lines.join("\n");
  const filePath = join(outputPath, "sow.sql");

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf-8");

  let totalRows = 0;
  for (const t of tables) totalRows += t.rows.length;

  return {
    format: "sql",
    outputPath,
    files: [filePath],
    totalSize: Buffer.byteLength(content, "utf-8"),
    tableCount: tables.length,
    rowCount: totalRows,
  };
}
